/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilCallback {
    }
    interface StencilOutraOrigem {
        "callback": () => any;
    }
}
declare global {
    interface HTMLStencilCallbackElement extends Components.StencilCallback, HTMLStencilElement {
    }
    var HTMLStencilCallbackElement: {
        prototype: HTMLStencilCallbackElement;
        new (): HTMLStencilCallbackElement;
    };
    interface HTMLStencilOutraOrigemElement extends Components.StencilOutraOrigem, HTMLStencilElement {
    }
    var HTMLStencilOutraOrigemElement: {
        prototype: HTMLStencilOutraOrigemElement;
        new (): HTMLStencilOutraOrigemElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-callback": HTMLStencilCallbackElement;
        "stencil-outra-origem": HTMLStencilOutraOrigemElement;
    }
}
declare namespace LocalJSX {
    interface StencilCallback {
    }
    interface StencilOutraOrigem {
        "callback"?: () => any;
    }
    interface IntrinsicElements {
        "stencil-callback": StencilCallback;
        "stencil-outra-origem": StencilOutraOrigem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-callback": LocalJSX.StencilCallback & JSXBase.HTMLAttributes<HTMLStencilCallbackElement>;
            "stencil-outra-origem": LocalJSX.StencilOutraOrigem & JSXBase.HTMLAttributes<HTMLStencilOutraOrigemElement>;
        }
    }
}
